create database RetailAnalysis

USE RetailAnalysis


/*DATA PREPARATION AND UNDERSTANDING*/
--1) What is the total number of rows in each of the 3 tables in the database?

SELECT count(Customer.customer_id) FROM Customer
SELECT count(prod_cat_info.prod_cat_code) FROM prod_cat_info
SELECT count(Transactions.cust_id) FROM Transactions

--2) What is the total number of transactions that have a return?

SELECT COUNT(transaction_id) AS Total_Returns
FROM Transactions
WHERE Qty<0;

--3) Convert the data variables into valid date formats before proceeding ahead. Dates are already in the correct data format so no need to convert the datatype 

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Customer' 
AND COLUMN_NAME = 'DOB';

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Transactions' 
AND COLUMN_NAME = 'tran_date';

--4) What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.

SELECT T.tran_date,
	YEAR(T.tran_date) AS Year_No,
		MONTH(T.tran_date) AS Month_No,
			DAY(T.tran_date) AS No_Of_Days
FROM Transactions T;

--5) Which product category does the sub-category"DIY" belong to?

SELECT prod_cat, prod_subcat 
FROM prod_cat_info P
WHERE prod_subcat = 'DIY';


/*DATA ANALYSIS*/

--1) Which channel is most frequently used for transactions?

SELECT TOP 1 Store_type, COUNT(transaction_id) AS No_of_Transactions
FROM Transactions
GROUP BY Store_type
ORDER BY No_of_Transactions DESC;


--2) What is the count of Male and Female customers in the database?

SELECT Gender, COUNT(Gender) AS Gender_Count
FROM Customer
WHERE Gender IS NOT NULL
GROUP BY Gender;

--3) From which city do we have the maximum number of customers and how many?

SELECT TOP 1 city_code, COUNT(customer_Id) AS Customer_Count
FROM Customer
GROUP BY city_code
ORDER BY Customer_Count DESC;


--4) How many sub-categories are there under the Books category?

SELECT prod_cat, COUNT(prod_subcat) AS sub_cat_count
FROM prod_cat_info
WHERE prod_cat = 'Books'
GROUP BY prod_cat;

--5) What is the maximum quantity of products ever ordered?



SELECT TOP 1 tran_date, transaction_id, SUM(Qty) AS Order_Qty
FROM Transactions
GROUP BY tran_date, transaction_id
ORDER BY Order_Qty DESC;




--6) What is the net total revenue generated in categories Electronics and Books?

SELECT P.prod_cat, SUM(T.total_amt) AS Net_Revenue
FROM Transactions T
JOIN prod_cat_info P
ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
WHERE P.prod_cat IN ('Electronics', 'Books')
GROUP BY P.prod_cat;




--7) How many customers have >10 transactions with us, excluding returns?
SELECT cust_id, COUNT(transaction_id) AS Transaction_Count
FROM Transactions
WHERE Qty>0
GROUP BY cust_id
HAVING COUNT(transaction_id)>10
ORDER BY Transaction_Count DESC;




--8) What is the combined revenue earned from the "Electronics" & "Clothing" categories, from "Flagship stores"?

SELECT SUM(X.Total_Revenue) AS Combined_Revenue
FROM
		(SELECT P.prod_cat, T.Store_type, SUM(T.total_amt) AS Total_Revenue
		FROM Transactions T
		JOIN prod_cat_info P
		ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
		GROUP BY P.prod_cat, T.Store_type) X
WHERE X.Store_type = 'Flagship store' AND X.prod_cat IN ('Electronics', 'Clothing');




--9) What is the total revenue generated from "Male" customers in "Electronics" category? Output should display total revenue by prod sub-cat

SELECT C.Gender, P.prod_subcat, SUM(T.total_amt) AS Total_Revenue
FROM Transactions T
JOIN Customer C
ON T.cust_id = C.customer_Id
JOIN prod_cat_info P
ON P.prod_cat_code = T.prod_cat_code AND P.prod_sub_cat_code = T.prod_subcat_code
WHERE C.Gender = 'M' AND P.prod_cat = 'Electronics'
GROUP BY C.Gender, P.prod_subcat;




--10) What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?


WITH CTE AS (
  SELECT 
    SUM(CASE WHEN T.total_amt > 0 THEN T.total_amt ELSE 0 END) AS Total_Sales,
    SUM(CASE WHEN T.total_amt < 0 THEN T.total_amt ELSE 0 END) AS Total_Returns
  FROM Transactions T
)
SELECT TOP 5 T.prod_subcat_code,
  100.0 * SUM(CASE WHEN T.total_amt > 0 THEN T.total_amt ELSE 0 END) / (SELECT total_sales FROM cte) AS Sales_Perc,
  100.0 * SUM(CASE WHEN T.total_amt < 0 THEN T.total_amt ELSE 0 END) / (SELECT total_returns FROM cte) AS Return_Perc
FROM Transactions T
GROUP BY T.prod_subcat_code
ORDER BY Sales_Perc DESC;



--Q11) For all customers aged between 25 to 35 years find what is the net total revenue generated by these
--consumers in last 30 days of transactions from max transaction date available in the data?


WITH CTE_MAX_DATE AS(
	SELECT MAX(tran_date) AS Max_date
	FROM Transactions T
			)
SELECT X.cust_id, X.Cust_Age, SUM(X.total_amt) AS Total_Revenue FROM (
		SELECT *, DATEADD(day, -30, cmd.Max_date) AS Min_date, DATEDIFF(year, C.DOB, cmd.Max_date) AS Cust_Age 
		FROM
		Transactions T
		JOIN Customer C ON T.cust_id = C.customer_Id
		CROSS JOIN CTE_MAX_DATE AS cmd) X
WHERE (X.Cust_Age BETWEEN 25 AND 35) AND (X.tran_date BETWEEN X.Min_date AND X.Max_date)
GROUP BY X.cust_id, X.Cust_Age;



--Q12) Which product category has seen the max value of returns in the last 3 months of transactions?

WITH CTE_MAX_DATE AS(
	SELECT MAX(tran_date) AS Max_date
	FROM Transactions T
			)
SELECT TOP 1 X.prod_cat, SUM(X.Qty) AS Total_Returns
FROM (
	SELECT P.prod_cat, T.Qty, T.tran_date, DATEADD(month, -3, cmd.Max_date) AS Min_Date, cmd.Max_date as Max_Date
	FROM Transactions T
	JOIN prod_cat_info P
	ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
	CROSS JOIN CTE_MAX_DATE AS cmd) X
WHERE (X.Qty < 0) AND (X.tran_date BETWEEN X.Min_Date AND X.Max_Date)
GROUP BY X.prod_cat
ORDER BY Total_Returns ASC;



--Q13) Which store-type sells the maximum products; by value of sales amount and by quantity sold?

 SELECT TOP 1 X.Store_type, X.Total_Qty_Sold, X.Total_Sales
 FROM
	 (SELECT T.Store_type, SUM(T.Qty) AS Total_Qty_Sold, SUM(T.total_amt) AS Total_Sales
	 FROM Transactions T
	 GROUP BY T.Store_type) X
 ORDER BY X.Total_Qty_Sold DESC, X.Total_Sales DESC;



--Q14) What are the categories for which average revenue is above the overall average

WITH CTE_Avg_Cat_Revenue AS(
	SELECT P.prod_cat, SUM(T.total_amt)/SUM(T.Qty) AS Cat_Avg
	FROM Transactions T
	JOIN prod_cat_info P
	ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
	GROUP BY P.prod_cat),
	
	CTE_Overall_Avg AS(
	SELECT SUM(T.total_amt)/SUM(T.Qty) AS Overall_Average
	FROM Transactions T
	)
SELECT *
FROM CTE_Avg_Cat_Revenue, CTE_Overall_Avg
WHERE CTE_Avg_Cat_Revenue.Cat_Avg > CTE_Overall_Avg.Overall_Average;



--Q15) Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

SELECT P.prod_subcat, SUM(T.total_amt) AS Total_Revenue,
		SUM(T.total_amt)/SUM(T.Qty) AS Average_Revenue
FROM Transactions T
JOIN prod_cat_info P
ON P.prod_cat_code = T.prod_cat_code AND P.prod_sub_cat_code = T.prod_subcat_code
WHERE P.prod_cat IN (SELECT TOP 5 P.prod_cat
					FROM Transactions T
					JOIN prod_cat_info P
					ON P.prod_cat_code = T.prod_cat_code AND P.prod_sub_cat_code = T.prod_subcat_code
					GROUP BY P.prod_cat
					ORDER BY SUM(T.total_amt) DESC)
GROUP BY P.prod_subcat;


